name: Auto Assign PR and Add Labels

on:
  pull_request:
    # Add edited since Jira GitHub bot edits the PR title after it's opened
    types: [opened, synchronize, edited]

jobs:
  auto-assign-and-label:
    # Skip the workflow if PR title is "chore: bump versions"
    if: "github.event.pull_request.title != 'chore: bump versions'"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assign PR to author
        id: autoAssign
        uses: actions/github-script@v7
        with:
          script: |
            const autoAssign = require('./.github/scripts/autoAssign.cjs');

            await autoAssign({ github, context, core });

      - name: Add label
        id: labeler
        uses: actions/github-script@v7
        with:
          script: |
            const addLabel = require('./.github/scripts/addLabel.cjs');

            await addLabel({ github, context, core });
