name: Post Merge

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup Artifacts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_PAT }}
          script: |
            const cleanupArtifacts = require('./.github/scripts/cleanupArtifacts.cjs')

            await cleanupArtifacts({ github, context, core })

  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout️
        uses: actions/checkout@v4

      - name: Notify in Jira
        uses: actions/github-script@v7
        env:
          JIRA_USER: '${{ secrets.JIRA_USER }}'
          JIRA_PASSWORD: '${{ secrets.JIRA_PASSWORD }}'
        with:
          script: |
            const postMerge = require('./.github/scripts/postMerge.cjs')

            await postMerge({ github, context, core }, fetch)
